name: React Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
   runs-on: ubuntu-latest

   strategy:
    matrix :
     node-versions: [16.x]

   steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-versions: ${{matrix.node-version}}
      - name: Installing packages
        run: npm ci
      - name: Build Making
        run: npm run build --if-present
      - name: Deploy to GitHub packages
        uses: crazy-max/ghaction-github-pages@v1
        with:
         target_branch: gh-pages
         build_dir: build
        env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}\