name: React Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
   runs-on: ubuntu-latest

   strategy:
    matrix :
     node-versions: [16.x]

   steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-versions: ${{matrix.node-version}}
      - name: Installing packages
        run: npm ci
      - name: Build Making
        run: npm run build --if-present
      - name: Deploy to GitHub packages
        uses: peaceiris/actions-gh-pages@v3
        with:
         deploy_key: ${{secrets.DEPLOY_TOKEN}}
         publish_dir: ./build